---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:BSON::Document
  value: "a.\t1 ó 0"
  checked: false
- !ruby/hash:BSON::Document
  value: "b.\t3536 o Perú"
  checked: false
- !ruby/hash:BSON::Document
  value: "c.\tVerdadero ó Falso"
  checked: false
- !ruby/hash:BSON::Document
  value: "d.\t=min(A1:A356)"
  checked: false
- !ruby/hash:BSON::Document
  value: "e.\ta y c"
  checked: true
