---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:BSON::Document
  value: "a.\tPara comparar el dato con toda la base de datos"
  checked: false
- !ruby/hash:BSON::Document
  value: "b.\tPara comparar el dato con el primer dato de la base de datos"
  checked: false
- !ruby/hash:BSON::Document
  value: "c.\tPara crear una condici贸n l贸gica con los datos correspondientes de la
    BD"
  checked: false
- !ruby/hash:BSON::Document
  value: "d.\tPara crear una condici贸n l贸gica en base al dato y haciendo referencia
    solo a la primera celda de la columna correspondiente de la base de datos"
  checked: true
