---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:BSON::Document
  value: "a.\tLa función Si + La función contar"
  checked: false
- !ruby/hash:BSON::Document
  value: "b.\tLa función Si + La función Contar (más de una vez)"
  checked: true
- !ruby/hash:BSON::Document
  value: "c.\tLa función contar + La función Si"
  checked: false
- !ruby/hash:BSON::Document
  value: "d.\tLa función Contar (más de una vez) + la función Si"
  checked: false
