---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- value: "a.\tHorizontal (Tienes en tus filas encabezados)"
  checked: false
- value: "b.\tVertical (Tienes en tus columnas Encabezados)"
  checked: true
- value: "c.\tSolo a y b"
  checked: false
- value: "d.\tN.A"
  checked: false
