---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:BSON::Document
  value: "a.\t=Espacios(sustituir(A1,carácter(160),””))"
  checked: false
- !ruby/hash:BSON::Document
  value: "b.\t=Espacios(Sustituir(A1,Carácter(160),” “))"
  checked: true
- !ruby/hash:BSON::Document
  value: "c.\t=sustituir(sustituir(A1,Carácter(160),” “),” “,””)"
  checked: false
- !ruby/hash:BSON::Document
  value: "d.\tN.A"
  checked: false
